# Разпознаване на навигация

Изграждайки си модел на HTML елементи да се провери дали използвайки линейна регресия можем да разпознаваме различни елементи от даден сайт, в частност основната навигация. 
Модела се базира на това елемента с какъв таг е дали е div nav или друг; дали в класовете на елемента присъстват nav, main, navigation, menu и прочие; колко линка се съдържат в зададеният елемент и колко от тях са на еднакаква дълбочина в DOM дървото.
    
Това което трябва да се добави е дълбочината на текущият елемент. И да се оптимизира да чете dataset-a от CSV

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import mglearn
from IPython.display import display

%matplotlib notebook

import warnings
warnings.filterwarnings(action="ignore", module="scipy", message="^internal gelsd")
warnings.filterwarnings(action="ignore", module="sklearn", message="^Objective did not")

# Зареждане на тестови данни

Използваме данни от [този spreadsheet](https://docs.google.com/spreadsheets/d/1cSLMdwg6C8A2C8guRnCAiOPvG3uovgmmPola6QxTSA8/) които са извадени с помощта на библиотека написана за целта.

в тях има обработени данни на следните сайтове:
- https://github.com/
- https://stackoverflow.com/
- https://www.youtube.com/
- https://www.telezueri.ch/
- https://www.wireltern.ch/
- https://www.wildeisen.ch/
- http://www.datecs.bg/
- https://www.ebay.com/
- https://www.amazon.com/
- https://www.bignerdranch.com/
- http://kolibriframework.io/
- https://www.microsoft.com/
- https://squareup.com
- https://www.apple.com/

In [2]:
y = [1,0,0,1,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0,1,0,0,1,0,1,0,0,1,0,1,0,0,1,0,0,1,0]
x = [[3,0,0,5,5],[1,0,0,7,7],[2,-1,0,29,29],
     [3,2,1,4,4],[1,0,0,21,7],[-1,-1,0,110,98],
     [2,1,1,11,10],[2,0,0,13,12],[3,0,0,4,4],
     [1,2,0,9,9],[-1,0,0,53,48],[3,0,0,5,5],
     [1,0,0,10,6],[-1,-1,0,51,45],[2,2,0,6,6],
     [1,1,0,10,10],[-1,1,0,51,45],[2,2,0,9,9],
     [-1,-1,0,1,1],[2,0,0,8,8],[1,0,0,14,9],
     [2,0,0,1,1],[2,2,0,34,28],[1,2,0,15,8],
     [3,2,0,7,7],[1,0,0,15,14],[-1,-1,0,34,33],
     [3,2,0,5,5],[-1,0,0,5,5],[3,2,1,21,21],
     [-1,0,0,28,21],[1,0,0,23,13],[3,0,1,8,5],
     [1,0,0,32,24],[-1,-1,0,78,43],[3,0,1,14,14],
     [-1,0,0,63,41]
    ]

In [3]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

Коефициенти за всеки параметър (feature) и константа на този модел са:

In [4]:
model.coef_, model.intercept_

(array([ 0.22168872,  0.08570927,  0.26697224, -0.00158637,  0.00565856]),
 -0.01612041997221536)

Успеваемостта на текущият модел е:

In [5]:
model.score(x, y)

0.668481082738593

# Тестване
Сега ще тестваме с навигацията на https://squareup.com

In [6]:
model.predict(np.array([[3,0,1,8,5]]))

array([0.93151979])

Сега да тестваме и с долната (footer) част на сайта на https://squareup.com

In [7]:
model.predict(np.array([[-1,-1,0,78,43]]))

array([-0.2039375])

Сега да видим какво ще изкара и за заглавната част на сайта, в която е и навигацията

In [8]:
model.predict(np.array([[1,0,0,32,24]]))

array([0.29060975])